version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
            
workflows:
  build-and-test:
    jobs:
      - aws-ecr/build-and-push-image:
          path: ./app/
          region: ${AWS_REGION}
          repo: ${CIRCLE_PROJECT_REPONAME}
          tag: latest
          filters:
            branches:
              only:
                - main
                - develop