# @Author: Rafael Direito
# @Date:   2022-10-05 18:25:06 (WEST)
# @Email:  rdireito@av.it.pt
# @Copyright: Insituto de Telecomunicações - Aveiro, Aveiro, Portugal
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2022-10-05 18:26:15 (WEST)


version: "3.8"
services:
    # rabbitmq3:
    #     container_name: "rabbitmq"
    #     image: rabbitmq:3.8-management-alpine
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=myuser
    #         - RABBITMQ_DEFAULT_PASS=mypassword
    #     ports:
    #         # AMQP protocol port
    #         - '5672:5672'
    #         # HTTP management UI
    #         - '15672:15672'
    cache:
        container_name: "redis-database"
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
